apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlopsmajor-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlopsmajor
  template:
    metadata:
      labels:
        app: mlopsmajor
    spec:
      containers:
      - name: mlopsmajor-container
        image: yashwanthravuri1234/mlopsmajor:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: mlopsmajor-service
spec:
  type: LoadBalancer
  selector:
    app: mlopsmajor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
